# Generated by Django 5.0.7 on 2024-07-15 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samasya', '0002_alter_category_options_samasya'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='samasya',
            options={'ordering': ('name',), 'verbose_name_plural': 'Samasya'},
        ),
    ]
